let shopItemsData = [
    {
      id: "a",
      name: "Women",
      price: 80,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/img-1.jpg",
    },
    {
      id: "b",
      name: "Women",
      price: 100,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/img-2.jpg",
    },
    {
      id: "c",
      name: "Women",
      price: 95,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/img-3.jpg",
    },
    {
      id: "d",
      name: "Women",
      price: 180,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/img-4.jpg",
    },
    {
      id: "e",
      name: "Women",
      price: 90,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/img-5.jpg",
    },
    {
      id: "f",
      name: "Women",
      price: 150,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/img-6.jpg",
    },
    {
      id: "g",
      name: "Women",
      price: 70,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/img-7.jpg",
    },
    {
      id: "h",
      name: "Women",
      price: 220,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/img-8.jpg",
    },
    {
      id: "i",
      name: "Man",
      price: 200,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/img-9.jpg",
    },
    {
      id: "j",
      name: "Man",
      price: 130,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/img-10.jpg",
    },
    {
      id: "k",
      name: "Man",
      price: 75,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/img-11.jpg",
    },
    {
      id: "l",
      name: "Man",
      price: 52,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/img-12.jpg",
    },
    {
      id: "m",
      name: "Man",
      price: 74,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/img-13.jpg",
    },
    {
      id: "n",
      name: "Man",
      price: 93,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/img-14.jpg",
    },
    {
      id: "o",
      name: "Man",
      price: 58,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/img-15.jpg",
    },
    {
      id: "p",
      name: "Man",
      price: 140,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
      img: "images/img-16.jpg",
    },
  ];